# Generated by Django 5.0.4 on 2024-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='inventory.vendorstaff'),
        ),
    ]
